inisialisasi training data

Male        = 0
Female      = 1

OverWeight  = 1
Under/Norml = 0 

In [248]:
import pandas as pd
import numpy as np

data =  pd.read_csv("bmi.csv")
print(data)

     Gender  Height  Weight  Index
0      Male     174      96      4
1      Male     189      87      2
2    Female     185     110      4
3    Female     195     104      3
4      Male     149      61      3
..      ...     ...     ...    ...
495  Female     150     153      5
496  Female     184     121      4
497  Female     141     136      5
498    Male     150      95      5
499    Male     173     131      5

[500 rows x 4 columns]


In [249]:
x_train = data[["Gender", "Height", "Weight"]].to_numpy()
y_train = data["Index"].to_numpy()

In [250]:
print(x_train)
print(y_train)

[['Male' 174 96]
 ['Male' 189 87]
 ['Female' 185 110]
 ...
 ['Female' 141 136]
 ['Male' 150 95]
 ['Male' 173 131]]
[4 2 4 3 3 3 5 5 3 4 2 4 3 2 2 5 5 5 5 5 5 5 4 5 2 3 3 1 5 5 5 1 1 5 5 4 3
 4 5 2 4 5 2 5 4 2 4 4 3 5 5 1 5 4 4 3 4 5 3 5 0 5 0 2 5 5 4 2 4 4 2 4 5 2
 3 4 4 4 4 0 3 5 3 4 5 0 5 5 5 5 5 3 3 2 4 5 4 5 1 0 4 5 5 4 4 4 5 5 4 3 4
 5 4 2 4 3 2 5 5 5 4 4 4 5 5 4 4 4 5 2 5 2 5 4 5 5 5 3 5 5 2 4 5 5 5 4 3 5
 3 3 0 3 3 5 5 4 3 5 3 4 2 2 3 5 4 2 4 5 3 2 4 5 5 4 4 4 4 3 5 3 3 4 4 2 3
 3 5 3 5 4 5 5 4 5 5 5 4 4 5 5 1 3 4 4 5 4 5 4 3 4 4 5 5 5 0 5 5 5 5 5 2 5
 4 5 0 5 3 4 5 5 4 2 3 3 4 3 5 5 2 5 3 2 1 5 0 5 3 5 3 4 3 5 5 5 5 2 4 5 5
 4 5 5 5 2 4 5 5 5 5 1 5 5 4 0 3 3 4 2 3 1 1 5 5 4 4 4 4 5 2 5 4 3 3 4 5 5
 2 4 3 4 5 4 2 4 5 4 5 5 1 5 5 5 5 2 2 5 3 5 4 5 4 4 5 5 4 2 2 4 3 3 5 4 2
 2 2 2 5 5 4 5 3 4 4 3 4 4 2 2 5 2 2 2 2 5 0 3 4 5 1 4 1 4 5 4 5 5 3 4 5 4
 3 5 1 2 4 5 5 5 5 3 5 1 4 5 5 2 5 4 3 2 2 2 2 3 5 3 3 5 3 5 3 4 2 4 4 5 2
 5 5 5 1 4 5 5 5 4 5 2 5 2 1 5 5 4 1 1 4 4 4 4 2 5 5 4 2 5 5

In [251]:
# persiapan data x

x_train[:,0] = np.where(x_train[:, 0] == "Male", 1, 0) # mengubah Male mejadi 1 dan Female 0
x_train[:,1] = x_train[:, 1]/np.max(x_train[:,1])
x_train[:,2] = x_train[:, 2]/np.max(x_train[:,2])
print(x_train)

[[1 0.8743718592964824 0.6]
 [1 0.949748743718593 0.54375]
 [0 0.9296482412060302 0.6875]
 ...
 [0 0.7085427135678392 0.85]
 [1 0.7537688442211056 0.59375]
 [1 0.8693467336683417 0.81875]]


In [252]:
#persiapan data y
y_train = np.where(y_train[:] < 3, 0, 1)
print(y_train)

[1 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 0 0 1 1 1 1
 1 1 0 1 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 0 0 1 1 1 0 1 1 0 1 1 0
 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1
 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 1 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0
 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1
 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0
 1 1 1 0 1 1 1 1 1 1 0 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1
 1 1 1 1 1 1 0 1 1 0 1 0 

CONFIGURE PERCEPTRON

In [253]:
weight = np.random.rand(3)
bias = np.random.rand(1)
output = np.zeros(1)
print(f" initial input : {weight}, initial bias : {bias}")

 initial input : [0.32172512 0.84479404 0.57892639], initial bias : [0.25639957]


Coba Model
y'   = w.x + b
f(x) = w.x + b

y'      =  prediksi terhadap x
f (x)   =  prediksi terhadap x
w       =  weight
x       =  nilai input layer
b       =  bias

In [254]:
y = np.sum(x_train[0] * weight) + bias
print(y)

[1.66414465]


MODEL FIT
Forward propagation & Error

MSE = 1 /n ( y - y') 
MSE = 1 /n ( error )

y  = nilai aktual 
y' = nilai prediksi
n  = jumlah data

In [255]:
# MSE = 0

# for i in range(len(x_train)):
#     y_predict = np.dot(x_train[i], weight) + bias
#     error = y_train[i] - y_predict
#     MSE   += error * error

# MSE = MSE / len(x_train)
# print(MSE)

Back Propagation dan Update Bobot

y/dw = w + learning_rate 

In [256]:
learning_rate   = 0.01
epoch           = 10

In [ ]:
def model_fit():
    global weight, bias
    # forward propagation

    MSE = 0
    d_weight = np.zeros(3)
    d_bias = np.zeros(1)

    for i in range(len(x_train)):
        y_predict = np.dot(x_train[i], weight) + bias
        error     = y_train[i] - y_predict
        MSE      += error*error
        
        d_weight += -2 * x_train[i] * error
        d_bias   += -2 * error

    d_weight /= len(x_train)
    d_bias   /= len(x_train)

    print(d_weight)

    # update parameters
    weight -= learning_rate * d_weight
    bias   -= learning_rate * d_bias
    print(MSE/len(x_train))

while(epoch > 0) :
    model_fit()
    epoch -= 1



UFuncTypeError: Cannot cast ufunc 'add' output from dtype('O') to dtype('float64') with casting rule 'same_kind'