Multilayer Perceptron

In [2]:
import numpy as np
import math

In [24]:
input_layer = np.array([
    [1,1],
    [1,0],
    [0,1],
    [0,0]
])

output_layer = np.array([1,0,0,1])

input = 2
hidden = 4
output = 1

def sigmoid(x):
    return 1/(1+np.exp(-x))

sig = np.vectorize(sigmoid)

In [ ]:
weight_hidden = np.random.uniform(low=-3, high=3, size=(input,hidden))
print("weight\n", weight_hidden)

bias_hidden = np.random.uniform(low=-3, high=3, size=(hidden))
print("bias\n", bias_hidden)

weight_output = np.random.uniform(low=-3, high=3, size=(hidden,output))
print("weight\n", weight_output)

bias_output = np.random.uniform(low=-3, high=3, size=(output))
print("bias\n", bias_output)


loss = []
accuracy = []



weight
 [[ 2.51390454 -1.75804692  2.11149688 -2.11570919]
 [-1.86484167 -2.480437   -0.04689192  2.97350895]]
bias
 [ 0.27784904 -1.5149657   2.62448523  2.65335122]
weight
 [[-0.05094426]
 [-2.36607355]
 [ 0.76840068]
 [ 1.3548115 ]]
bias
 [-1.84543988]


Feedforward

In [32]:
epochs = 1
lr = 0.1

In [ ]:
for epoch in range(epochs):
    MSE = 0
    new_target = np.zeros(output_layer.shape)
    
    for idx, inp in enumerate(input_layer):
        o_hidden = np.matmul(input_layer[idx], weight_hidden) + bias_hidden
        o_hidden = sig(o_hidden)
        print("--------")
        print(o_hidden)

        o_output = np.matmul(o_hidden, weight_output) + bias_output
        o_output = sig(o_output)
        print(o_output)

        error = output_layer[idx] - o_output
        MSE = MSE + (error*error)
        new_target[idx] = o_output.round()



--------
[0.71644836 0.00316179 0.99088873 0.97100339]
[0.54673971]
--------
[0.94222857 0.03650871 0.99130248 0.63126372]
[0.41026682]
--------
[0.16980743 0.01806759 0.92940553 0.99641305]
[0.54171974]
--------
[0.56901881 0.18020404 0.93242088 0.93421724]
[0.42100648]
